name: MakeCode

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js $\{{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: $\{{ matrix.node-version }}
      - name: npm install
        run: |
          npm install -g pxt
          pxt target arcade
      - name: build
        run: |
          pxt clean
          pxt install --hw samd51
          pxt build --hw samd51 --cloud
          cp built/binary.uf2 samd51.uf2
          pxt clean
          pxt install --hw stm32f401
          pxt build --hw stm32f401 --cloud
          cp built/binary.uf2 stm32f401.uf2          
        env:
          CI: true
